spring:
  config:
    active:
      on-profiles: prod

build:
  version: 1.0

contact:
  message: Welcome to eazybank accounts microservice production owner contact
  contactDetails:
    name: Amila Kumara - production owner
    email: akumara@eazrybank.com
  onCallSupport:
    - (456) 456-7891
    - (456) 654-3220
