spring:
  config:
    active:
      on-profile: prod

build:
  version: 1.0

contact:
  message: Welcome to eazybank cards microservice production owner contact
  contactDetails:
    name: Amila Kumara - Production owner
    email: amila@eazrybank.com
  onCallSupport:
    - (456) 456-7891
    - (456) 654-3220