build:
  version: 3.0

contact:
  message: Welcome to eazybank loans microservice developer contact
  contactDetails:
    name: Yasura Laksitha - developer
    email: yasura.dev@gmail.com
  onCallSupport:
    - (555) 456-7890
    - (555) 654-3210